jobs:
  build:
    runs-on: ubuntu-latest  # Changed from self-hosted to ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Adjust this to your Ruby version
